#Numpy

https://numpy.org/doc/stable/reference/random/index.html


In [1]:
import numpy as np

import matplotlib.pyplot as pyplot

In [2]:
# Default RNG = Random Number Generator

rng = np.random.default_rng() # default range is between 0 and 1

In [3]:
# Return random floats in the half open interval [0.0, 1.0) - different brackets

# A half-open interval includes only one of its endpoints, and is denoted by mixing 
# the notations for open and closed intervals. For example, (0,1] means greater than 0 and 
# less than or equal to 1, while [0,1) means greater than or equal to 0 and less than 1


rng.random(7)

array([0.40795409, 0.20275422, 0.24803376, 0.68570814, 0.9664297 ,
       0.83898613, 0.63245861])

In [4]:
# Generate Numbers on a standard normal distribution
# The mean = 0.0, stdev = 1.0
# i.e. Bell curve
# the numbers generated should be on average centered on 0.0
# More than 99% of the numbers generated should be between (in the interval) -3.0 and 3.0

rng.standard_normal(10)

array([ 0.63890575,  1.6164025 , -1.24142282,  1.29271142,  0.01961803,
       -1.515336  , -0.2361985 ,  1.53900177,  0.12942486,  1.68590836])

In [5]:
# Generates random integers between 0 (included) and 10 (excluded)

rng.integers(low=0, high=10, size=5)

array([8, 6, 8, 0, 5])